# See https://www.gitpod.io/docs/configure/workspaces
tasks:
  - init: make init-env
    before: IMG_TOOL=docker GOPROXY= make build-ext copy-ext build-image
    command: cd console/atest-ui/ && npm i

ports:
  - port: 5713  # console interactive port
