header:
  license:
    spdx-id: Apache License
    copyright-owner: API Testing Authors

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure
