---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-testing
  name: api-testing
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-testing
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-testing
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: api-testing
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - image: ghcr.io/linuxsuren/api-testing
        name: server
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: api-testing
spec:
  ports:
  - name: grpc
    port: 7070
    protocol: TCP
    targetPort: 7070
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-testing
  sessionAffinity: None
  type: NodePort
