{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api-testing.fullname" . }}-servicemonitor
  labels:
    {{- include "api-testing.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "api-testing.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}