# permissions for end users to view atests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: atest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: atest-viewer-role
rules:
- apiGroups:
  - core.linuxsuren.github.com
  resources:
  - atests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.linuxsuren.github.com
  resources:
  - atests/status
  verbs:
  - get
