---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.linuxsuren.github.com
  resources:
  - atests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.linuxsuren.github.com
  resources:
  - atests/finalizers
  verbs:
  - update
- apiGroups:
  - core.linuxsuren.github.com
  resources:
  - atests/status
  verbs:
  - get
  - patch
  - update
