#!api-testing
# yaml-language-server: $schema=https://linuxsuren.github.io/api-testing/api-testing-schema.json
# https://docs.gitlab.com/ee/api/api_resources.html
name: atest
api: |
  {{default "http://localhost:8080/server.Runner" (env "SERVER")}}
items:
- name: suites
  request:
    api: /GetSuites
    method: POST
- name: createSuite
  request:
    api: /CreateTestSuite
    method: POST
    body: |
      {"name": "{{randAlpha 6}}"}
- name: suite
  request:
    api: /GetTestSuite
    method: POST
    body: |
      {"name": "{{randAlpha 6}}"}
  expect:
    bodyFieldsExpect:
      name: ""
      api: ""
- name: UpdateTestSuite
  request:
    api: /UpdateTestSuite
    method: POST
    body: |
      {
        "name": "{{index (keys .suites.data) 0}}",
        "api": "{{randAlpha 6}}"}
      }
- name: DeleteTestSuiteNotFound
  request:
    api: /DeleteTestSuite
    method: POST
    body: |
      {"name": "{{randAlpha 6}}"}
  expect:
    statusCode: 500

- name: ListTestCase
  request:
    api: /ListTestCase
    method: POST
    body: |
      {"name": "{{index (keys .suites.data) (randInt 0 (len (keys .suites.data)))}}"}
- name: list-testcases-not-found
  request:
    api: /ListTestCase
    method: POST
    body: |
      {"name": "{{randAlpha 6}}"}
  expect:
    bodyFieldsExpect:
      name: ""
- name: GetSuggestedAPIs-no-testsuite-found
  request:
    api: /GetSuggestedAPIs
    method: POST
    body: |
      {"name": "{{randAlpha 6}}"}
  expect:
    verify:
      - len(data.data) == 0
- name: get-testcase-not-found
  request:
    api: /GetTestCase
    method: POST
    body: |
      {"name": "test"}
  expect:
    statusCode: 500
    bodyFieldsExpect:
      code: 2
- name: get-popular-headers
  request:
    api: /PopularHeaders
    method: POST

- name: list-code-generators
  request:
    api: /ListCodeGenerator
    method: POST
  expect:
    verify:
      - len(data) == 1
- name: GenerateCode
  request:
    api: /GenerateCode
    method: POST
    body: |
      {
        "TestSuite": "{{index (keys .suites.data) 0}}",
        "TestCase": "{{randAlpha 6}}",
        "Generator": "golang"
      }
  expect:
    statusCode: 500 # no testcase found
    verify:
      - indexOf(data.message, "not found") != -1

- name: listConverters
  request:
    api: /ListConverter
    method: POST
  expect:
    verify:
      - len(data) == 1
- name: ConvertTestSuite
  request:
    api: /ConvertTestSuite
    method: POST
    body: |
      {
        "TestSuite": "{{index (keys .suites.data) 0}}",
        "Generator": "jmeter"
      }
  expect:
    verify:
      - data.message != ""
      - indexOf(data.message, "jmeterTestPlan") != -1

- name: list-stores
  request:
    api: /GetStores
    method: POST
  expect:
    verify:
      - len(data) >= 1
- name: query-funcs
  request:
    api: /FunctionsQuery
    method: POST
  expect:
    verify:
      - len(data) == 1
- name: version
  request:
    api: /GetVersion
    method: POST
- name: GetSecrets
  request:
    api: /GetSecrets
    method: POST
  expect:
    statusCode: 500

- name: DeleteTestSuite
  request:
    api: /DeleteTestSuite
    method: POST
    body: |
      {"name": "{{index (keys .suites.data) 0}}"}
