#!api-testing
# yaml-language-server: $schema=https://linuxsuren.github.io/api-testing/api-testing-schema.json
# see also https://github.com/LinuxSuRen/api-testing
name: trpc-sample
api: ip://127.0.0.1:8000
spec:
  kind: trpc
  rpc:
    import:
      - ./bin
    protofile: ./bin/helloworld.proto
items:
  - name: Hello
    request:
      api: Hello
      body: |
        {
          "msg": "atest"
        }
    expect:
      verify:
        - data.msg == "Hello atest!"
