name: File Lint Check

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  files-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - uses: ./tools/github-actions/setup-deps
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.1.0
        with:
          node-version: "21"

      - name: Markdown Lint check
        run: |
          make lint.markdown

      - name: Yaml Lint check
        run: |
          make lint.yaml

      - name: Check License
        run: |
          make lint.checklicense

      - name: Check Code Spell
        run: |
          make lint.codespell
